#! /bin/sh

#first
# This file looks through all the files in the current
# directory for the atring POSIX, and then prints the manes of
# those files to the standard output

for file in *
do
	if grep -q POSIX $file
	then
		echo $file
	fi
done

exit 0

